FROM alpine:3.22
LABEL org.opencontainers.image.authors="matt@horwood.biz"

RUN apk update                     \
    && apk add unit-php84 \
    && rm -f /var/cache/apk/*;

COPY config /config

ENTRYPOINT ["/config/start_unit.sh"]
CMD ["unitd", "--no-daemon", "--state /config/;"]
