FROM alpine:3.18
MAINTAINER Matthew Horwood <matt@horwood.biz>

RUN apk update                     \
    && apk add unit-php81 \
    && rm -f /var/cache/apk/*;

COPY config /config

ENTRYPOINT ["/config/start_unit.sh"]
CMD ["unitd", "--no-daemon", "--state /config/;"]
